import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: { debateId: string } }
) {
  try {
    const debateId = params.debateId
    
    // Forward request to FastAPI backend
    const backendResponse = await fetch(`http://localhost:8000/ai-debate/download/${debateId}`, {
      method: 'GET',
    })
    
    if (!backendResponse.ok) {
      throw new Error(`Backend request failed: ${backendResponse.status}`)
    }
    
    // Get the file content from backend
    const fileContent = await backendResponse.text()
    
    // Return as downloadable file
    return new NextResponse(fileContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename=ai_debate_transcript_${debateId}.txt`,
      },
    })
    
  } catch (error) {
    console.error('Download API error:', error)
    
    // Return fallback transcript
    const timestamp = new Date().toLocaleString()
    const fallbackContent = `AI EXPERT DEBATE TRANSCRIPT
Generated: ${timestamp}
Debate ID: ${params.debateId}

=================================================
PARTICIPANTS:
[S] Dr. Sarah Chen - The Skeptical Researcher
[O] Prof. Alex Rivera - The Optimistic Innovator  
[A] Dr. Morgan Kim - The Data-Driven Analyst
=================================================

ROUND 1: INITIAL PERSPECTIVES
[Dr. Sarah Chen]: I'm concerned about the methodology here. How can we verify the statistical significance?

[Prof. Alex Rivera]: This is exciting! The implications could revolutionize the entire field!

[Dr. Morgan Kim]: We need to examine the empirical evidence before drawing conclusions.

ROUND 2: RESPONSES & REBUTTALS
[Dr. Sarah Chen]: Where's the peer review? What about confounding variables?

[Prof. Alex Rivera]: You're missing the bigger picture - think about breakthrough applications!

[Dr. Morgan Kim]: Let's focus on correlation coefficients and statistical significance.

=================================================
GENERATED BY: Document Insight System
POWERED BY: Gemini 2.5 Flash + Azure Speech Services
FEATURE: AI Expert Debate
=================================================
`
    
    return new NextResponse(fallbackContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename=ai_debate_transcript_${params.debateId}.txt`,
      },
    })
  }
}
